name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: [ "main "]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 300
          repositories_forks: yes
          commits_authoring: wasp@wasp.dev
          plugin_achievements: yes
          plugin_notable: yes
          plugin_achievements_limit: 10
          plugin_achievements_ignored: gister, chatter
